version: "3.8"
services:
    db:
        image: postgres:15.1-alpine
        restart: always
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: $DB_USER_NAME #postgres
            POSTGRES_PASSWORD: $DB_PASSWORD #1234
            PGDATA: /var/lib/postgresql/data
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
volumes:
    db-data: