version: "3.9"

services:
  db:
    image: postgres:12.6-alpine
    ports:
      - 54320:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 65430:6543
    env_file:
      - .env
    volumes:
      - ./backend/api:/usr/src/app/wifibbsms
    depends_on:
      - db
